name: >-
  On: Repo Created

run-name: >-
  ${{ inputs.owner }}/${{ inputs.repo }} > Repo Created

on:
  workflow_dispatch:
    inputs:
      owner:
        description: owner
        required: true
      repo:
        description: repo
        required: true

jobs:
  actions:
    name: Actions
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.owner }}/${{ inputs.repo }}/${{ github.workflow }}/actions
      cancel-in-progress: true
    steps:
      - name: Set Default Workflow Permissions
        # https://docs.github.com/en/rest/actions/permissions#set-default-workflow-permissions-for-a-repository
        run: >-
          gh api '/repos/${{ inputs.owner }}/${{ inputs.repo }}/actions/permissions/workflow'
          --field default_workflow_permissions='read'
          --field can_approve_pull_request_reviews=true
          --method PUT
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

  copier:
    name: Copier
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.owner }}/${{ inputs.repo }}/${{ github.workflow }}/copier
      cancel-in-progress: true
    steps:
      - id: auth
        name: Auth App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repo }}
      - id: branches
        name: Get Branches
        run: |-
          n_branches="$(gh api "/repos/${{ inputs.owner }}/${{ inputs.repo }}/branches" --jq 'length')"
          echo "n_branches=$n_branches" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.auth.outputs.token }}
      - if: ${{ steps.branches.outputs.n_branches > 0 }}
        name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ steps.auth.outputs.token }}
      - if: ${{ steps.branches.outputs.n_branches > 0 }}
        name: Copier Update
        uses: liblaf/actions/copier-update@main
      - if: ${{ steps.branches.outputs.n_branches > 0 }}
        name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(copier): update from template"
          commit_user_name: ${{ steps.auth.outputs.committer-name }}
          commit_user_email: ${{ steps.auth.outputs.committer-email }}
          commit_author: ${{ steps.auth.outputs.author }}

  label:
    name: Label
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.owner }}/${{ inputs.repo }}/${{ github.workflow }}/label
      cancel-in-progress: true
    steps:
      - id: auth
        name: Auth App
        uses: liblaf/actions/auth-app@main
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ inputs.owner }}
          repositories: ${{ inputs.repo }}
        # TODO: remove download labels until <https://github.com/Financial-Times/github-label-sync/issues/193> is resolved
      - name: Download Labels
        run: >-
          wget --output-document='labels.yaml'
          'https://raw.githubusercontent.com/${{ inputs.owner }}/.github/main/.github/labels.yaml'
      - name: GitHub Label Sync
        run: >-
          npx github-label-sync
          --access-token '${{ steps.auth.outputs.token }}'
          --labels 'labels.yaml'
          --allow-added-labels
          '${{ inputs.owner }}/${{ inputs.repo }}'

  repo:
    name: Repo
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.owner }}/${{ inputs.repo }}/${{ github.workflow }}/repo
      cancel-in-progress: true
    steps:
      - name: Edit Repository Setttings
        run: >-
          gh repo edit '${{ inputs.owner }}/${{ inputs.repo }}'
          --allow-update-branch
          --delete-branch-on-merge
          --enable-auto-merge
          --enable-discussions
          --enable-issues
          --enable-merge-commit=false
          --enable-rebase-merge=false
          --enable-squash-merge
          --enable-wiki=false
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}

  ruleset:
    name: Ruleset
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.owner }}/${{ inputs.repo }}/${{ github.workflow }}/ruleset
      cancel-in-progress: true
    steps:
      - name: Ruleset Import
        # TODO: switch to gh cli until <https://github.com/cli/cli/issues/8019> is resolved
        uses: liblaf/actions/ruleset-import@main
        with:
          repo: ${{ inputs.owner }}/${{ inputs.repo }}
          token: ${{ secrets.GH_PAT }}
          source-repo: liblaf/.github
          source-ruleset-id: 3407904

  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ inputs.owner }}/${{ inputs.repo }}/${{ github.workflow }}/secrets
      cancel-in-progress: true
    steps:
      - name: Create or Update Secrets
        run: |-
          function secret-set() {
            gh secret --repo '${{ inputs.owner }}/${{ inputs.repo }}' set "$1" --body "$2"
          }

          secret-set CARGO_REGISTRY_TOKEN '${{ secrets.CARGO_REGISTRY_TOKEN }}'
          secret-set GH_APP_ID '${{ secrets.GH_APP_ID }}'
          secret-set GH_APP_PRIVATE_KEY '${{ secrets.GH_APP_PRIVATE_KEY }}'
          secret-set GH_PAT '${{ secrets.GH_PAT }}'
          secret-set NPM_TOKEN '${{ secrets.NPM_TOKEN }}'
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
